version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tyk_postgres_db
    ports:
      - "5432:5432"
    environment:
      # These values are now read from the .env file
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - tyk-db-data:/var/lib/postgresql/data  # Stores PostgreSQL data in a named volume to prevent data loss across rebuilds and updates.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  tyk-db-data: